174,0
S,SignatureGF2,Internal,0,1,0,0,0,0,0,0,0,267,,160,-38,-38,-38,-38,-38
S,SignatureGF2,Internal,1,0,1,-10,0,262,1,0,0,0,0,0,0,0,-10,,160,-38,-38,-38,-38,-38
S,SignatureGF2,Internal,0,1,0,0,0,0,0,0,0,148,,160,-38,-38,-38,-38,-38
S,SignatureGF2,Internal,1,0,1,216,0,319,1,0,0,0,0,0,0,0,216,,160,-38,-38,-38,-38,-38
S,SignatureMatrix,Returns a matrix S and a list U of generators of Z_K^*. The i-th row of S contains the signature of U[i],1,0,1,-9,0,262,1,0,0,0,0,0,0,0,-9,,177,82,-38,-38,-38,-38
S,SignatureMatrix,Returns a matrix S and a list U of generators of Z_K^*. The i-th row of S contains the signature of U[i],0,1,0,0,0,0,0,0,0,262,,177,82,-38,-38,-38,-38
S,SignatureMatrix,Returns a matrix S and a list U of generators of Z_K^*. The i-th row of S contains the signature of U[i],0,1,0,0,0,0,0,0,0,319,,177,82,-38,-38,-38,-38
S,SignatureMatrix,Returns a matrix S and a list U of generators of Z_K^*. The i-th row of S contains the signature of U[i],1,0,1,215,0,319,1,0,0,0,0,0,0,0,215,,177,82,-38,-38,-38,-38
S,UnitWithSignature,"Returns true iff there exists a unit in Z_K that has signature vector sig. If so, the second return value contains a list of all such units modulo squares",1,0,1,-9,0,262,2,0,0,0,0,0,0,0,160,,0,0,-9,,36,82,-38,-38,-38,-38
S,UnitWithSignature,"Returns true iff there exists a unit in Z_K that has signature vector sig. If so, the second return value contains a list of all such units modulo squares",0,2,0,0,0,0,0,0,0,160,,0,0,262,,36,82,-38,-38,-38,-38
S,UnitWithSignature,"Returns true iff there exists a unit in Z_K that has signature vector sig. If so, the second return value contains a list of all such units modulo squares",0,2,0,0,0,0,0,0,0,160,,0,0,319,,36,82,-38,-38,-38,-38
S,UnitWithSignature,"Returns true iff there exists a unit in Z_K that has signature vector sig. If so, the second return value contains a list of all such units modulo squares",1,0,1,215,0,319,2,0,0,0,0,0,0,0,160,,0,0,215,,36,82,-38,-38,-38,-38
S,UnitWithSigns,"Returns true iff there exists a unit in Z_K that has signature vector sig. If so, the second return value contains a list of all such units modulo squares",3,0,1,-9,0,262,1,1,82,0,332,2,1,82,0,148,3,0,0,0,0,0,0,0,82,,0,0,82,,0,0,-9,,82,-38,-38,-38,-38,-38
S,UnitWithSigns,"Returns true iff there exists a unit in Z_K that has signature vector sig. If so, the second return value contains a list of all such units modulo squares",2,1,1,82,0,147,2,1,82,0,148,3,0,0,0,0,0,0,0,82,,0,0,82,,0,0,262,,82,-38,-38,-38,-38,-38
S,MakeTotallyPositive,"Returns true iff there exists some unit u in Z_K with u*x totally positive. If this is the case, then the second return value lists all such units u (modulo squares)",1,0,1,-10,0,262,1,0,0,0,0,0,0,0,-10,,36,82,-38,-38,-38,-38
S,MakeTotallyPositive,"Returns true iff there exists some unit u in Z_K with u*x totally positive. If this is the case, then the second return value lists all such units u (modulo squares)",0,1,0,0,0,0,0,0,0,267,,36,82,-38,-38,-38,-38
S,MakeTotallyPositive,"Returns true iff there exists some unit u in Z_K with u*x totally positive. If this is the case, then the second return value lists all such units u (modulo squares)",0,1,0,0,0,0,0,0,0,148,,36,82,-38,-38,-38,-38
S,MakeTotallyPositive,"Returns true iff there exists some unit u in Z_K with u*x totally positive. If this is the case, then the second return value lists all such units u (modulo squares)",1,0,1,216,0,319,1,0,0,0,0,0,0,0,216,,36,82,-38,-38,-38,-38
S,HasTotallyPositiveGenerator,"Check if I can be generated by a totally positive element. If so, the second return value is such a generator",0,1,0,0,0,0,0,0,0,324,,36,82,-38,-38,-38,-38
